/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiclient;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Scanner;

/**
 *
 * @author HP
 */
public class GUI extends javax.swing.JFrame {

   Socket s;
   String userName;
   ClientConnection cc;
   DataInputStream din;
   DataOutputStream dout;
   boolean shouldRun= true;
   private final static String newline = "\n";

    
    public GUI() {
        initComponents();
        messageField.setText("Welcome");
        
    }

   
    
    
    public class ClientConnection implements Runnable{
        Socket s;
        String uName;
        
    
    public ClientConnection(Socket socket,String name ){
        s=socket;
        this.uName=name;
    }
    
    
    public void sendStringToServer(String text,String name){
        try{
            dout.writeUTF(name+":"+text);
            dout.flush();
        }catch(IOException e){
            e.printStackTrace();
            close();
        }
        
    }
    
    public void run(){
        
        try{
            din=new DataInputStream(s.getInputStream());
            dout=new DataOutputStream(s.getOutputStream());
             while(shouldRun){
            try{
                while(din.available() == 0){
                    try{
                        Thread.sleep(1);
                    }catch(InterruptedException e){
                        e.printStackTrace();
                    }
                }
                
                String reply=din.readUTF();
             /*   if(reply.contains("BYE")){
                    
                    close();
                    System.out.println("User disconnected");
                    shouldRun=false;
                    messageField.append(newline+userName+" has disconnected");
                }*/
                messageField.append(newline+reply);
                System.out.println(reply);
                
            }catch(IOException e){
                e.printStackTrace();
                close();
            }
        }
        }catch(IOException e){
            e.printStackTrace();
        }
       
    }
    
    public void close() {
        try {
            din.close();
            dout.close();
            s.close();
            
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        typeField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        connectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageField.setColumns(20);
        messageField.setRows(5);
        jScrollPane1.setViewportView(messageField);

        typeField.setColumns(20);
        typeField.setRows(5);
        jScrollPane2.setViewportView(typeField);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MESSAGES");

        nameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameField.setText("Enter your name");

        connectBtn.setText("CONNECT");
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        String reply="";
        reply=typeField.getText().toString();
        if(reply.contains("BYE")){
            messageField.append(newline+"disconnected");
            shouldRun=false;
            try{
            dout.writeUTF(userName+":"+reply);
            dout.flush();
            
        }catch(IOException e){
            e.printStackTrace();
            close();
            
        }
        }else{
        try{
            dout.writeUTF(userName+":"+reply);
            dout.flush();
            
        }catch(IOException e){
            e.printStackTrace();
            close();
            
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        try{
            
            s=new Socket("localhost",3333);     
            userName=nameField.getText().toString();
            announceNewUser(s,userName);
            
           
            
            
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_connectBtnActionPerformed
    
    
public void announceNewUser(Socket s,String userName){
    
    Thread t=new Thread(new ClientConnection(s,userName));
    t.start();
    
}   
     public void close() {
        try {
            din.close();
            dout.close();
            s.close();
            
        }catch(IOException e){
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea typeField;
    // End of variables declaration//GEN-END:variables
}
